### ISSUE TITLE
ROS Vive Tracker terminate called after throwing an instance of 'std::logic_error'   what():  basic_string::_M_construct null not valid

### ISSUE THREAD

**Issue by ortasa** [abhijitmajumdar/ViveTracker#2]
Hello,
I tried to run roslaunch vive_tracker_ros_package vive_tracker_ros.launch and get the following error:"ROS Vive Tracker terminate called after throwing an instance of 'std::logic_error'   what():  basic_string::_M_construct null not valid"

Attached the log file:
[roslaunch-roman-desktop-12276.log]
(https://github.com/abhijitmajumdar/ViveTracker/files/2407793/roslaunch-roman-desktop-12276.log)

I would be grateful if you could help me solve the problem.
Thanks,
Ortal

roman@roman-desktop:~/catkin_ws/src/ViveTracker$ roslaunch vive_tracker_ros_package vive_tracker_ros.launch
... logging to /home/roman/.ros/log/b8c80d72-be60-11e8-be3b-b8aeed7e3645/roslaunch-roman-desktop-10132.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://roman-desktop:36641/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /vive_tracker_node/calibrate: True
 * /vive_tracker_node/config_file: /home/roman/catki...

NODES
  /
    vive_tracker_node (vive_tracker_ros_package/vive_tracker_ros_node)

auto-starting new master
process[master]: started with pid [10142]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to b8c80d72-be60-11e8-be3b-b8aeed7e3645
process[rosout-1]: started with pid [10155]
started core service [/rosout]
process[vive_tracker_node-2]: started with pid [10165]
ROS Vive Tracker
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
[vive_tracker_node-2] process has died [pid 10165, exit code -6, cmd /home/roman/catkin_ws/src/ViveTracker/vive_tracker_ros/vive_tracker_ros_package/vive_tracker_ros_node __name:=vive_tracker_node __log:=/home/roman/.ros/log/b8c80d72-be60-11e8-be3b-b8aeed7e3645/vive_tracker_node-2.log].
log file: /home/roman/.ros/log/b8c80d72-be60-11e8-be3b-b8aeed7e3645/vive_tracker_node-2*.log

**Comment by abhijitmajumdar** [comment]
@ortasa see if a ROS_NAMESPACE is defined in the environment variables? On a terminal do
`export ROS_NAMESPACE=somename`
_somename_ being an arbitrary name you could change

**Comment by ortasa** [comment]
It solved the problem.
Thank you,
Ortal
